root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main ."
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  include_ext = ["go", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false

